<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="main_tests.HelloWorldTest-20230222225026" tests="1" file="main_tests.py" time="0.014" timestamp="2023-02-22T22:50:27" failures="1" errors="0" skipped="0">
	<testcase classname="main_tests.HelloWorldTest" name="test_should_issue_hello_world_message" time="0.014" timestamp="2023-02-22T22:50:27">
		<failure type="VerificationError" message="
Wanted but not invoked:

    write('Hello world')

Instead got:

    write('Hello World')

"><![CDATA[Traceback (most recent call last):
  File "C:\Users\Brandon Local\AppData\Local\Programs\Python\Python310\lib\unittest\case.py", line 59, in testPartExecutor
    yield
  File "C:\Users\Brandon Local\AppData\Local\Programs\Python\Python310\lib\unittest\case.py", line 591, in run
    self._callTestMethod(testMethod)
  File "C:\Users\Brandon Local\AppData\Local\Programs\Python\Python310\lib\unittest\case.py", line 549, in _callTestMethod
    method()
  File "c:\users\brandon local\desktop\cpp\spring 2023\swe\kanqichao\src\unittest\python\main_tests.py", line 12, in test_should_issue_hello_world_message
    verify(out).write("Hello world")
  File "c:\users\brandon local\desktop\cpp\spring 2023\swe\kanqichao\target\venv\build\cpython-3.10.2.final.0\lib\site-packages\mockito\invocation.py", line 275, in __call__
    self.verification.verify(self, len(matched_invocations))
  File "c:\users\brandon local\desktop\cpp\spring 2023\swe\kanqichao\target\venv\build\cpython-3.10.2.final.0\lib\site-packages\mockito\verification.py", line 94, in verify
    raise VerificationError(
mockito.verification.VerificationError: 
Wanted but not invoked:

    write('Hello world')

Instead got:

    write('Hello World')


]]></failure>
	</testcase>
</testsuite>
